server:
  port: 8880

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/company/**, /api/user/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: company-service
                fallbackUri: forward:/fb/company

        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/content/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: content-service
                fallbackUri: forward:/fb/content

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"