server:
  port: 8881

spring:
   datasource:
     url: jdbc:postgresql://postgres:5432/apppush
     username: ${DB_USERNAME:postgres}
     password: ${DB_USERNAME:postgres}
jpa:
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
    ddl-auto: update
    open-in-view: false

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:app-eureka-server}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://app-eureka-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"