server:
  port: 8882

spring:
  application:
    name: content-service
  rabbitmq:
    username: root
    password: root
  cloud:
    stream:
      bindings:
        output:
          destination: apppush

  datasource:
    url: jdbc:mysql://mysql:3306/apppush
    username: root
    password: root
jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto: update

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:app-eureka-server}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://app-eureka-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"