server:
  port: 8081

spring:
   datasource:
     url: jdbc:postgresql://localhost:5432/apppush
     username: postgres
     password: postgres
jpa:
  database: postgresql
  show-sql: true
  hibernate:
    ddl-auto: update
    open-in-view: false