server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}