server:
  port: 8883

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  cloud:
    stream:
      bindings:
        input:
          destination: apppush

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:http://localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/